# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cedabc5ac22eb56dcb9cfb8d8976ca5dd7f63c2ec843fdd71a43e1648bde3d9c161dfec70095c134dacb56cee1f3afc6627a391d4b48f57a408afe06e3f05fc

test:
  secret_key_base: 605745db763b0f61529b368a4f3f5504d128b6abcac0f6edfc1affb8c43e356702dde7553237c29605dec8b26b6195bd470f2c3fd948937e46975f5478ca92ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
